---
- name: Create system group
  group:
    name: "{{ wikijs_system_group }}"
    system: true

- name: Create system user
  user:
    name: "{{ wikijs_system_user }}"
    group: "{{ wikijs_system_group }}"
    groups: "{{ wikijs_user_additional_groups }}"
    comment: "Service account for wikijs."
    create_home: false
    shell: /usr/sbin/nologin
    system: true

- name: Check if Wiki.js is already installed
  stat:
    path: "{{ wikijs_download_dest }}"
  register: wikijsinstalled

- name: "Does Wiki.js directory exist?"
  file:
    path: "{{ wikijs_download_dest }}"
    state: directory

- name: Download and extract Wiki.js
  unarchive:
    src: "{{ wikijs_download_url }}"
    remote_src: true
    dest: "{{ wikijs_download_dest }}/"
    owner: "{{ wikijs_system_user }}"
    group: "{{ wikijs_system_group }}"
  when: not wikijsinstalled.stat.exists or wikijs_update
  notify:
    - Restart Wiki.js

# Used when user or group changes
- name: Set ownership
  file:
    path: "{{ wikijs_download_dest }}/"
    owner: "{{ wikijs_system_user }}"
    group: "{{ wikijs_system_group }}"
    recurse: true
  when: |
    wikijsinstalled.stat.pw_name is undefined or wikijsinstalled.stat.pw_name != wikijs_system_user
    or wikijsinstalled.stat.gr_name is undefined or wikijsinstalled.stat.gr_name != wikijs_system_group

- name: Deploy config.yml
  template:
    src: config.yml.j2
    dest: "{{ wikijs_download_dest }}/config.yml"
    owner: "{{ wikijs_system_user }}"
    group: "{{ wikijs_system_group }}"
    mode: 0640
  notify: Restart Wiki.js

- name: Copy service file
  template:
    src: wiki.service.j2
    dest: "/etc/systemd/system/wiki.service"
    owner: root
    group: root
    mode: 0640
  notify:
    - Reload systemctl daemon
    - Enable Wiki.js service
    - Restart Wiki.js

- name: Flush handlers
  meta: flush_handlers
