---
- name: Reload systemctl daemon
  systemd:
    daemon_reload: true

- name: Enable Wiki.js service
  service:
    name: wiki
    enabled: true

- name: Restart Wiki.js
  service:
    name: wiki
    state: restarted
